#### =====================================================
#### =============== experiment setting ==================
#### =====================================================
doing: 'test'
save: False ## save visualization or not

## example
experiment_name: 'UNet_Abdomen_CT2MR_pmt'
data_root: '/mnt/ExtData/Data/processed/chaos/'
save_root: '/mnt/ExtData/SFDA_DDFP/log/revise/test'
target_sites:
- 'mr'
dataset_name: 'abdomen'

ori_model_path: '/mnt/ExtData/SFDA_DDFP/log/abdominal/src_train/UNet_Abdomen_CT_Seg/T2023-11-30 10:12:34_/saved_models/best_model_epoch_92_dice_0.9289.pth' ## ori use for visualization
source_model_path: '/mnt/ExtData/SFDA_DDFP/log/revise/UNet_Abdomen_CT2MR_pmt/ablation_cls/T2024-11-06 23:14:51_ftLSET1_Pmt_UNet_Data_w1110_cls30/saved_models/best_model_step_4_dice_0.8874.pth'

wcls: 
- 40 
- 40
- 40
- 40
- 40
wglo: 0.4
alpha: 0.8
theta: 0.2

pmt_type: 'Data' # choice : None | Data | Domain | Spatial
train_type: 'LSET1' # choice : pmt | LSET1 | All | pmtinc | besideLSET1 | LSET1wodown3 | LSET1wodown23
pmt_size: 256
es_step: 10 #5
resume_dir: ''
continue_train: False
total_epochs: 10

random_seed: 999
organ_list:
- 'Liver'
- 'R.Kidney'
- 'L.Kidney'
- 'Spleen'
# ---------
# - 'AA'
# - 'LAC'
# - 'LVC'
# - 'MYO'
# ---------
# - 'Tumor'


# Dataloader Setting
patient_level_dataloader: False
img_size:
- 256
- 256
batch_size: 16
num_workers: 8

# Model 
arch: 'Pmt_UNet'
# arch: 'UNet'
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 64
num_classes: 5
num_prototypes: 1

# Loss parameters
nav_t: 1
beta: 0.001
s_par: 0.5
dice_ignore_index: -1
# display
save_steps: 500
eval_steps: 2 #4
display_steps: 20
save_visuals: True

# test
test: False